---
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.llamaStack.postgresql.name }}-credentials
  namespace: {{ .Values.global.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
stringData:
  POSTGRES_DB: {{ .Values.llamaStack.postgresql.database }}
  POSTGRES_USER: {{ .Values.llamaStack.postgresql.user }}
  POSTGRES_PASSWORD: {{ .Values.llamaStack.postgresql.password }}
type: Opaque