---
apiVersion: v1
kind: Namespace
metadata:
  name: lls-playground
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-stack-playground
  namespace: lls-playground
  labels:
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/version: "latest"
---
apiVersion: v1
kind: Service
metadata:
  name: llama-stack-playground
  namespace: lls-playground
  labels:
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/version: "latest"
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: llama-stack-playground
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: llama-stack-playground
  namespace: lls-playground
  labels:
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/version: "latest"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: llama-stack-playground
  template:
    metadata:
      labels:
        app.kubernetes.io/name: llama-stack-playground
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: llama-stack-playground
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            readOnlyRootFilesystem: false
            runAsNonRoot: true
          image: "quay.io/rh-aiservices-bu/llama-stack-playground:0.2.11"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8501
              protocol: TCP
          env:
            - name: STREAMLIT_BROWSER_GATHER_USAGE_STATS
              value: "false"
            - name: STREAMLIT_SERVER_ADDRESS
              value: "0.0.0.0"
            - name: STREAMLIT_SERVER_PORT
              value: "8501"
            - name: LLAMA_STACK_ENDPOINT
              value: "$LLS_ENDPOINT"
            - name: DEFAULT_MODEL
              value: "llama-4-scout-17b-16e-w4a16"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
          resources:
            limits:
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: lls-playground-lls-playground
spec:
  href: "https://pg-lls-playground.apps.$CLUSTER_DOMAIN"
  location: ApplicationMenu
  text: LLS Playground
  applicationMenu:
    section: OpenShift Self Managed Services
    imageURL: https://static.wikia.nocookie.net/fortnite_gamepedia/images/3/3a/T-T-Icon-BR-SM-Athena-SupplyLlama-01.png
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: pg
  namespace: lls-playground
  labels:
    app.kubernetes.io/name: llama-stack-playground
    app.kubernetes.io/version: "latest"
spec:
  to:
    kind: Service
    name: llama-stack-playground
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
