{{- if .Values.RAG.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name:  ingestion-secret
  namespace: {{ .Values.global.namespace }}{{ .Values.pipelines.namespaceSuffix }}
  labels:
    app: {{ .Values.llamaStack.name }}
stringData:
  LLAMA_STACK_URL: "http://{{ .Values.llamaStack.name }}-service.{{ .Values.global.namespace }}.svc.cluster.local:8321"
  VECTOR_DB_ID: {{ .Values.RAG.vector_db_id | quote }}
  GIT_REPO: {{ .Values.RAG.git_repo | quote }}
  GIT_BRANCH: {{ .Values.RAG.git_branch | quote }}
  GIT_DOCS_PATH: {{ .Values.RAG.git_docs_path | quote }}
  GIT_TOKEN: {{ .Values.RAG.git_token | quote }}
type: Opaque
{{- end }}