---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.gradioUI.name }}-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gradioUI.name }}
data:
  chat_prompt: |-
    {{- tpl ($.Files.Get "conf/app/chat_prompt.md") . | nindent 4 }}
  form_prompt: |-
    {{- tpl ($.Files.Get "conf/app/form_prompt.md") . | nindent 4 }}
  # Form tab configuration
  form_sampling_params: {{ .Values.gradioUI.config.form_tab.sampling_params | toJson | quote }}
  form_tools: {{ .Values.gradioUI.config.form_tab.tools | toJson | quote }}
  form_max_infer_iters: {{ .Values.gradioUI.config.form_tab.max_infer_iters | quote }}
  # Chat tab configuration
  chat_sampling_params: {{ .Values.gradioUI.config.chat_tab.sampling_params | toJson | quote }}
  chat_tools: {{ .Values.gradioUI.config.chat_tab.tools | toJson | quote }}
  chat_max_infer_iters: {{ .Values.gradioUI.config.chat_tab.max_infer_iters | quote }}
  # ArgoCD configuration
  argocd_base_url: {{ .Values.gradioUI.config.argocd.base_url | quote }}
  argocd_api_token: {{ .Values.gradioUI.config.argocd.api_token | quote }}
  # GitHub configuration
  github_auth_token: {{ .Values.gradioUI.config.github.auth_token | quote }}
  github_toolsets: {{ .Values.gradioUI.config.github.toolsets | quote }}
  github_readonly: {{ .Values.gradioUI.config.github.readonly | quote }}
  