---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.gradioUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gradioUI.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  replicas: {{ .Values.gradioUI.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.gradioUI.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.gradioUI.name }}
      # annotations:
      #   checksum/config: {{ printf "%s-%s-%s-%s-%s-%s-%s" (.Values.gradioUI.config.form_tab.sampling_params | toJson) (.Values.gradioUI.config.form_tab.tools | toJson) (.Values.gradioUI.config.chat_tab.sampling_params | toJson) (.Values.gradioUI.config.chat_tab.tools | toJson) (.Values.gradioUI.config.argocd | toJson) (tpl ($.Files.Get "conf/app/chat_prompt.txt") .) (tpl ($.Files.Get "conf/app/form_prompt.txt") .) | sha256sum | trunc 63 }}
    spec:
      terminationGracePeriodSeconds: 5
      serviceAccountName: {{ .Values.gradioUI.serviceAccount.name | default "default" }}
      containers:
        - name: {{ .Values.gradioUI.name }}
          image: "{{ .Values.gradioUI.image.repository }}:{{ .Values.gradioUI.image.tag | default "latest" }}"
          imagePullPolicy: {{ .Values.gradioUI.image.pullPolicy | default "" }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop:
                - ALL
          ports:
            - name: http
              containerPort: 7860
              protocol: TCP
          env:
            - name: GRADIO_SERVER_NAME
              value: 0.0.0.0
            - name: GRADIO_SERVER_PORT
              value: '7860'            
            - name: LLAMA_STACK_URL
              value: 'http://{{ .Values.llamaStack.name }}-service.{{ .Values.global.namespace }}:8321'
            - name: LOG_LEVEL
              value: "{{ .Values.gradioUI.env.LOG_LEVEL | default "INFO" }}"
            - name: GITHUB_GITOPS_REPO
              value: "{{ .Values.gradioUI.env.GITHUB_GITOPS_REPO | default "" }}"
          envFrom:
            # Mount all ConfigMap entries as environment variables
            # ConfigMap keys must match env var names (e.g., CHAT_PROMPT, FORM_GENERATE_RESOURCES_PROMPT, etc.)
            - configMapRef:
                name: {{ .Values.gradioUI.name }}-config
            # Mount all Secret entries as environment variables
            # Secret keys must match env var names (e.g., ARGOCD_BASE_URL, GITHUB_PAT, etc.)
            - secretRef:
                name: {{ .Values.gradioUI.name }}-config
          livenessProbe:
            httpGet:
              path: "/"
              port: 7860
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: "/"
              port: 7860
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          {{- with .Values.gradioUI.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
