---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.gradioUI.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.gradioUI.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  to:
    kind: Service
    name: {{ .Values.gradioUI.name }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: "edge"
    insecureEdgeTerminationPolicy: "Redirect"
