---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: {{ .Values.llamaStack.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
spec:
  replicas: 1
  server:
    distribution:
      {{- if .Values.llamaStack.image }}
      image: {{ .Values.llamaStack.image | quote }}
      {{- else }}
      name: rh-dev
      {{- end }}
    containerSpec:
      resources:
        requests:
          memory: "500Mi"
          cpu: "100m"
        limits:
          memory: "8Gi"
          cpu: "2"
      # command:
      #   - /bin/sh
      #   - '-c'
      #   - llama stack run /etc/llama-stack/run.yaml
      env:

        #########################
        # Metadata backend
        #########################
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              key: POSTGRES_HOST
              name: {{ .Values.llamaStack.name }}-secret
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              key: POSTGRES_DB
              name: {{ .Values.llamaStack.name }}-secret
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: POSTGRES_USER
              name: {{ .Values.llamaStack.name }}-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ .Values.llamaStack.name }}-secret

        #########################
        # Embeddings provider
        #########################

        {{- if .Values.llamaStack.embeddings.remote }}
        # Option 2: Remote embeddings (MaaS)
        - name: VLLM_EMBEDDING_URL
          valueFrom:
            secretKeyRef:
              key: VLLM_EMBEDDING_URL
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_EMBEDDING_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: VLLM_EMBEDDING_API_TOKEN
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_EMBEDDING_MAX_TOKENS
          valueFrom:
            secretKeyRef:
              key: VLLM_EMBEDDING_MAX_TOKENS
              name: {{ .Values.llamaStack.name }}-secret

        {{- else }}
        # Option 2: Inline embeddings (sentence-transformers)
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: "true"
        - name: EMBEDDING_PROVIDER
          value: "sentence-transformers"
        {{- end }}

        #########################
        # Inference provider
        #########################

        - name: INFERENCE_MODEL
          valueFrom:
            secretKeyRef:
              key: INFERENCE_MODEL
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_URL
          valueFrom:
            secretKeyRef:
              key: VLLM_URL
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_TLS_VERIFY
          valueFrom:
            secretKeyRef:
              key: VLLM_TLS_VERIFY
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: VLLM_API_TOKEN
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_MAX_TOKENS
          value: "65536"


        #########################
        # Tooling providers
        #########################

        {{- if .Values.llamaStack.websearch.tavilyApiKey }}
        - name: TAVILY_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              key: TAVILY_SEARCH_API_KEY
              name: {{ .Values.llamaStack.name }}-secret
        {{- end }}

        {{- if .Values.mcpServers }}
        - name: MCP_OCP_URL
          valueFrom:
            secretKeyRef:
              key: MCP_OCP_URL
              name: {{ .Values.llamaStack.name }}-secret
        - name: MCP_ARGOCD_URL
          valueFrom:
            secretKeyRef:
              key: MCP_ARGOCD_URL
              name: {{ .Values.llamaStack.name }}-secret
        - name: MCP_SERVICENOW_URL
          valueFrom:
            secretKeyRef:
              key: MCP_SERVICENOW_URL
              name: {{ .Values.llamaStack.name }}-secret
        {{- end }}

    # {{- if .Values.mcpServers }}
    # # Default config in /opt/app-root/run.yaml
    # userConfig:
    #   configMapName: {{ .Values.llamaStack.name }}-config
    # {{- end }}
    # storage:
    #   size: "20Gi"
      # mountPath: "/opt/app-root/src/.llama/distributions/rh-dev"