---
apiVersion: llamastack.io/v1alpha1
kind: LlamaStackDistribution
metadata:
  name: {{ .Values.llamaStack.name }}
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
spec:
  replicas: 1
  network:
    allowedFrom:
      namespaces:
        - intelligent-cd
        - intelligent-cd-pipelines
    exposeRoute: {{ .Values.llamaStack.ingress.enabled }}
  server:
    distribution:
      {{- if .Values.llamaStack.image }}
      image: {{ .Values.llamaStack.image | quote }}
      {{- else }}
      name: rh-dev
      {{- end }}
    # storage:
    #   size: 5Gi
    containerSpec:
      resources:
        requests:
          memory: "500Mi"
          cpu: "250m"
        limits:
          memory: "12Gi"
          cpu: "4"
      env:

        #########################
        # Metadata backend
        #########################
        - name: POSTGRES_HOST
          value: {{ .Values.llamaStack.postgresql.name }}.{{ .Values.global.namespace }}.svc.cluster.local
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: {{ .Values.llamaStack.postgresql.database | quote }}
        - name: POSTGRES_USER
          value: {{ .Values.llamaStack.postgresql.user | quote }}
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: POSTGRES_PASSWORD
              name: {{ .Values.llamaStack.name }}-secret

        #########################
        # Embeddings provider
        #########################

        {{- if .Values.llamaStack.embeddings.remote }}
        - name: VLLM_EMBEDDING_URL
          value: {{ .Values.llamaStack.embeddings.url | quote }}
        - name: VLLM_EMBEDDING_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: VLLM_EMBEDDING_API_TOKEN
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_EMBEDDING_MAX_TOKENS
          value: {{ .Values.llamaStack.embeddings.maxTokens | quote }}
        {{- else }}
        - name: ENABLE_SENTENCE_TRANSFORMERS
          value: "true"
        - name: EMBEDDING_PROVIDER
          value: "sentence-transformers"
        {{- end }}

        #########################
        # Inference provider
        #########################

        - name: INFERENCE_MODEL
          value: {{ .Values.inference.model | quote }}
        - name: VLLM_URL
          value: {{ .Values.inference.url | quote }}
        - name: VLLM_TLS_VERIFY
          value: {{ .Values.inference.tlsVerify | quote }}
        - name: VLLM_API_TOKEN
          valueFrom:
            secretKeyRef:
              key: VLLM_API_TOKEN
              name: {{ .Values.llamaStack.name }}-secret
        - name: VLLM_MAX_TOKENS
          value: "{{ .Values.inference.maxTokens | default 400000 }}"

        #########################
        # Tooling providers
        #########################

        {{- if .Values.llamaStack.websearch.tavilyApiKey }}
        - name: TAVILY_SEARCH_API_KEY
          valueFrom:
            secretKeyRef:
              key: TAVILY_SEARCH_API_KEY
              name: {{ .Values.llamaStack.name }}-secret
        {{- end }}

        {{- if .Values.mcpServers }}
        {{- if .Values.mcpServers.ocpMcpServer }}
        - name: MCP_OCP_URL
          value: "http://{{ .Values.mcpServers.ocpMcpServer.name }}:{{ .Values.mcpServers.ocpMcpServer.mcpServer.port }}"
        {{- end }}
        {{- if .Values.mcpServers.argocdMcpServer }}
        - name: MCP_ARGOCD_URL
          value: "http://{{ .Values.mcpServers.argocdMcpServer.name }}:{{ .Values.mcpServers.argocdMcpServer.mcpServer.port }}"
        {{- end }}
        {{- if .Values.mcpServers.servicenowMcp }}
        - name: MCP_SERVICENOW_URL
          value: "http://{{ .Values.mcpServers.servicenowMcp.name }}:{{ .Values.mcpServers.servicenowMcp.mcpServer.port }}"
        {{- end }}
        {{- end }}

        #########################
        # OpenTelemetry
        #########################

        {{- if .Values.llamaStack.opentelemetry.enabled }}
        - name: OTEL_SERVICE_NAME
          value: {{ .Values.llamaStack.opentelemetry.otelServiceName | quote }}
        - name: TELEMETRY_SINKS
          value: {{ .Values.llamaStack.opentelemetry.telemetrySinks | quote }}
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: {{ .Values.llamaStack.opentelemetry.otelExporterOtlpEndpoint | quote }}
        {{- end }}
