---
kind: Secret
apiVersion: v1
metadata:
  name:  {{ .Values.llamaStack.name }}-secret
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.llamaStack.name }}
stringData:
  VLLM_API_TOKEN: {{ .Values.inference.apiToken | quote }}
  POSTGRES_PASSWORD: {{ .Values.llamaStack.postgresql.password | quote }}
{{- if .Values.llamaStack.websearch.tavilyApiKey }}
  TAVILY_SEARCH_API_KEY: {{ .Values.llamaStack.websearch.tavilyApiKey | quote }}
{{- end }}
{{- if .Values.llamaStack.embeddings.remote }}
  VLLM_EMBEDDING_API_TOKEN: {{ .Values.llamaStack.embeddings.apiToken | quote }}
{{- end }}
type: Opaque
